### ISSUE TITLE
python package not found even tho its already installed 

### ISSUE THREAD

**Issue by 1923812371283127398123712893126793** [Hysocs/Obscura#1]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Obscura-main\main.py", line 7, in <module>
    from Core.obfuscator import CodeObfuscator
  File "C:\Users\User\Desktop\Obscura-main\Core\obfuscator.py", line 7, in <module>
    from Core.encryptor import CodeEncryptor
  File "C:\Users\User\Desktop\Obscura-main\Core\encryptor.py", line 6, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by Hysocs** [comment]
To set up a virtual environment in VS Code and install the required packages, follow these steps:

1. **Open the project in VS Code.**

2. **Open the terminal in VS Code:**
   - You can open the terminal by clicking on `Terminal` in the top menu and then selecting `New Terminal`, or by using the shortcut `` Ctrl+` ``.

3. **Create a virtual environment:**
   - In the terminal, run the following command to create a virtual environment named `venv`:
     ```sh
     python -m venv venv
     ```

4. **Activate the virtual environment:**
   - For Windows:
     ```sh
     .\venv\Scripts\activate
     ```
   - For macOS and Linux:
     ```sh
     source venv/bin/activate
     ```

5. **Redownload the updated `requirements.txt` file.** I have updated the `requirements.txt` file, so please make sure you have the latest version.

6. **Install the required packages:**
   - With the virtual environment activated, run the following command to install the packages listed in `requirements.txt`:
     ```sh
     pip install -r requirements.txt
     ```

After completing these steps, the virtual environment should be set up with all the necessary dependencies installed.

**Comment by Hysocs** [comment]
Just wanted to check in and see if you got it working. If not, I can help you on Discord to solve the problem.

**Comment by 1923812371283127398123712893126793** [comment]
> Just wanted to check in and see if you got it working. If not, I can help you on Discord to solve the problem.

yes it worked

**Comment by Hysocs** [comment]
If you have any other issues, such as specific files not working after obfuscation, and disabling certain settings doesn't fix it, please open a new issue.
